version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports: 
      - "8080:8080"
    environment:
      GIN_MODE: "debug"
      SENTRY_DSN: "https://sentry.io"
    volumes:
      - .:/app/api